baseURL: "https://fmuiin14.github.io/"
languageCode: en-us
title: FathulMuiin
theme: PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON
    
params:
  defaultTheme: auto # to switch between dark or light according to browser theme
  assets:
    disableFingerprinting: true
  homeInfoParams:
    Title: "Hello 👋 I'm Fathul."
    Content: "Welcome to my blog. You can find my portofolio and my posts here. I'm a Backend Engineer based in West Java, Indonesia. You can me reach at 👇👇👇"
  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/fmuiin/"
    - name: twitter
      url: "https://twitter.com/rukawa_san"
    - name: instagram
      url: "https://instagram.com/fmuiin"
    - name: linkedin
      url: "https://linkedin.com/in/fmuiin14"
    - name: medium
      url: "https://medium.com/@fmuiin14"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/10955266/fathul-muiin"
    - name: github
      url: "https://github.com/fmuiin14"
      
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  # enableEmoji: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50